package com.bookstore.entity;
// Generated 2019-05-29 00:20:05 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bookstoredb")
public class Book implements java.io.Serializable {

	private int bookId;
	private Book book;
	private String title;
	private String author;
	private String description;
	private String sibn;
	private byte[] image;
	private float price;
	private Date publishedDate;
	private Date lastUpdateTime;
	private Set<ReviewTable> reviewTables = new HashSet<ReviewTable>(0);
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	private Set<Book> books = new HashSet<Book>(0);

	public Book() {
	}

	public Book(int bookId, Book book, String title, String author, String description, String sibn, byte[] image,
			float price, Date publishedDate, Date lastUpdateTime) {
		this.bookId = bookId;
		this.book = book;
		this.title = title;
		this.author = author;
		this.description = description;
		this.sibn = sibn;
		this.image = image;
		this.price = price;
		this.publishedDate = publishedDate;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Book(int bookId, Book book, String title, String author, String description, String sibn, byte[] image,
			float price, Date publishedDate, Date lastUpdateTime, Set<ReviewTable> reviewTables,
			Set<OrderDetail> orderDetails, Set<Book> books) {
		this.bookId = bookId;
		this.book = book;
		this.title = title;
		this.author = author;
		this.description = description;
		this.sibn = sibn;
		this.image = image;
		this.price = price;
		this.publishedDate = publishedDate;
		this.lastUpdateTime = lastUpdateTime;
		this.reviewTables = reviewTables;
		this.orderDetails = orderDetails;
		this.books = books;
	}

	@Id

	@Column(name = "book_id", unique = true, nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Author", nullable = false, length = 64)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "description", nullable = false, length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sibn", nullable = false, length = 15)
	public String getSibn() {
		return this.sibn;
	}

	public void setSibn(String sibn) {
		this.sibn = sibn;
	}

	@Column(name = "Image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "published_date", nullable = false, length = 10)
	public Date getPublishedDate() {
		return this.publishedDate;
	}

	public void setPublishedDate(Date publishedDate) {
		this.publishedDate = publishedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<ReviewTable> getReviewTables() {
		return this.reviewTables;
	}

	public void setReviewTables(Set<ReviewTable> reviewTables) {
		this.reviewTables = reviewTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
